# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dde290e94fad1b2281896d6044618e208e92e4ed4a39756517ad0ac368a8a46d96c50c0cf092276285708fd40efcfa013e060ec817d99eff743d51c2d71ab9dc

test:
  secret_key_base: cf407c4641be81c9c19fc0e305eb3352e63c4dc7c8dc1357c13a21736d5e6fa329b82e5e0bd46d7c4fb34a5c584e48f8874506fe6658096c6ddb2fee6447f2db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
